[project]
name = "charybdis"
description = "Tiny Hi-Rez API wrapper."
version = "1"
requires-python = ">=3.9"
dependencies = ["httpx"]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
